import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";

const kanit = Kanit({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["thai"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`kanit ${kanit.className} antialiased`}>
        {children}

        <div className="text-center text-gray-900" font-bold mt-20>
          <hr className="w-2x1 mx-auto" />
          Create By Hexx
          <br />
          Copyringt &copy; 2025
        </div>
      </body>
    </html>
  );
}
